# see: https://github.com/probot/settings

repository:
  name: action.deploy-ecs-service
  description: Github action to apply updated container images to an ECS service
  topics: action
  private: false
  has_issues: false
  has_wiki: false
  is_template: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  archived: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
